create table tb_course (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_degree (generation_date datetime(6), id bigint not null auto_increment, student_id bigint, team_id bigint, code varchar(255), primary key (id)) engine=InnoDB;
create table tb_month_payment (discount float(53), paid bit not null, payday date, price float(53), id bigint not null auto_increment, student_id bigint, team_id bigint, primary key (id)) engine=InnoDB;
create table tb_registration (discount float(53), paid bit not null, payday date, price float(53), received float(53), id bigint not null auto_increment, student_id bigint, team_id bigint, primary key (id)) engine=InnoDB;
create table tb_student (date_birth date, id bigint not null auto_increment, cpf varchar(255), name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table tb_team (completed bit not null, course_id bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_team_student (student_id bigint not null, team_id bigint not null) engine=InnoDB;
alter table tb_degree add constraint FKibrjmfgngvoqmn6xi9mpjtoyx foreign key (student_id) references tb_student (id);
alter table tb_degree add constraint FKdl2pspijuld2bqx8bt842l3tk foreign key (team_id) references tb_team (id);
alter table tb_month_payment add constraint FKbiup0ohpbt2tsqr4gewng3x3i foreign key (student_id) references tb_student (id);
alter table tb_month_payment add constraint FKpsc959113rsxgl2889avu2l2c foreign key (team_id) references tb_team (id);
alter table tb_registration add constraint FK64g8q3y1b2j4obkhn92109gtk foreign key (student_id) references tb_student (id);
alter table tb_registration add constraint FK1xyr1axlec0qvk96oiwn07ttt foreign key (team_id) references tb_team (id);
alter table tb_team add constraint FK4k5ly6q6g4m6aqb0yq3eaullg foreign key (course_id) references tb_course (id);
alter table tb_team_student add constraint FK5rxqeth1uqbbd56c6cojl9h78 foreign key (team_id) references tb_team (id);
alter table tb_team_student add constraint FK3kx2m34a0g40svwnjircqjrwx foreign key (student_id) references tb_student (id);
INSERT INTO tb_course (name) VALUES ('flebotomia');
INSERT INTO tb_team (name, completed, course_id) VALUES ('ctf0123', false, 1);
INSERT INTO tb_team (name, completed, course_id) VALUES ('ctf0223', false, 1);
INSERT INTO tb_student (name, phone, date_birth, cpf) VALUES ('Odair Guimarães Pereira', '81992208527', '1900-01-01', '102.940.284-12');
INSERT INTO tb_student (name, phone, date_birth, cpf) VALUES ('Maria Fabielle Soares Da Silva', '81991100809', '1900-02-01', '125.962.574-59');
INSERT INTO tb_student (name, phone, date_birth, cpf) VALUES ('Maria Fernanda da Silva Oliveira', '81998440931', '1900-03-01', '115.897.914-28');
INSERT INTO tb_student (name, phone, date_birth, cpf) VALUES ('Luzia de Melo Valenca', '81998452127', '1900-05-01', '093.041.524-88');
INSERT INTO tb_team_student (student_id, team_id) VALUES (1, 1);
INSERT INTO tb_team_student (student_id, team_id) VALUES (2, 1);
INSERT INTO tb_team_student (student_id, team_id) VALUES (3, 2);
INSERT INTO tb_team_student (student_id, team_id) VALUES (4, 2);
INSERT INTO tb_registration (price, discount, received, paid, payday, student_id, team_id) VALUES (150, 0, 75, false, '2023-07-13', 1, 1);
INSERT INTO tb_registration (price, discount, received, paid, payday, student_id, team_id) VALUES (150, 0, 0, false, '2023-07-13', 2, 1);
INSERT INTO tb_registration (price, discount, received, paid, payday, student_id, team_id) VALUES (150, 0, 130, false, '2023-07-13', 3, 2);
INSERT INTO tb_registration (price, discount, received, paid, payday, student_id, team_id) VALUES (150, 0, 0, false, '2023-07-13', 4, 2);
INSERT INTO tb_month_payment (price, discount, paid, payday, student_id, team_id) VALUES (170, 0, false, '2023-08-01', 1, 1);
INSERT INTO tb_month_payment (price, discount, paid, payday, student_id, team_id) VALUES (170, 20, false, '2023-08-01', 2, 1);
INSERT INTO tb_month_payment (price, discount, paid, payday, student_id, team_id) VALUES (170, 0, false, '2023-08-01', 3, 2);
INSERT INTO tb_month_payment (price, discount, paid, payday, student_id, team_id) VALUES (170, 20, false, '2023-08-01', 4, 2);
INSERT INTO tb_degree (code, generation_date, student_id, team_id) VALUES ('CTF0123-A94BG1-230707-151845', '2023-07-07 15:24:45', 1, 1);
